compressionLevel: mixed

enableGlobalCache: false

enableTelemetry: false

nodeLinker: pnp

npmRegistries:
  //npm-proxy.docplanner.io/:
    npmAlwaysAuth: true
    npmAuthToken: yhS20AZxhSjLVKQsMxlSC3IDnTVWtrHBh8rR6wJJtJH+3FhP1541gBX1dJvtlTaze+Ja7l67yEb4FsaEROnHZxp6kleJqRELZT7qex/lBQM=
  //npm.pkg.github.com/:
    npmAlwaysAuth: true
    npmAuthToken: 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

npmScopes:
  docplanner:
    npmRegistryServer: "https://npm.pkg.github.com/"
  dp-vue:
    npmRegistryServer: "https://npm-proxy.docplanner.io/"
  dp-watson-web:
    npmRegistryServer: "https://npm-proxy.docplanner.io/"

yarnPath: .yarn/releases/yarn-4.1.0.cjs
