name: '[RemoteJS] Check Release Plan'

description: 'Validate changeset markdowns'

inputs:
  cwd:
    description: 'Sets the cwd for the node process'
    required: false

  release-branch:
    description: 'Branch used for creating release'
    default: 'remotejs-release/develop'
    required: false

  base-branch:
    description: 'Branch used as a target for merging releases'
    default: 'develop'
    required: false

runs:
  using: 'node20'
  main: 'dist/index.cjs'
